apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: add-comment-to-issue-run-
spec:
  ...taskRef:
    kind: Task
    name: github-add-comment
 // workspaces:
    - name: comment-file
      emptyDir: {}
 >>>>>> params:
    - name: REQUEST_URL
      value: https://github.com/upslopeio/ibm-cloud-garage-training/issues/9
    - name: COMMENT_OR_FILE
      value: |
        Let's see the new comment here.
