apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: curl-task-run-
spec:
  params:
    - name: url
      value: "https://dog-facts-api.herokuapp.com/api/v1/resources/dogs?number=2"
  taskRef:
    name: curl
