---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tekton-task-assignment
spec:
  steps:
    ddd- name: retrieve-yaml
      image: quay.io/ibmgaragecloud/alpine-curl
      script: |
        pwd
        mkdir k8s
        cd k8s
        curl https://raw.githubusercontent.com/tektoncd/pipeline/main/examples/v1beta1/taskruns/run-steps-as-non-root.yaml | head -n 24 | sed 's/ubuntu/quay.io\/ibmgaragecloud\/alpine-curl/g' run-steps-as-non-root-task-only.yaml
