---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata: 
  name: tekton-task-assignment
spec: 
  steps: 
    - name: retrieve-yaml
      image: quay.io/ibmgaragecloud/alpine-curl
      script: |
        pwd
        mkdir k8s
        cd k8s
        curl https://raw.githubusercontent.com/tektoncd/pipeline/main/examples/v1beta1/taskruns/run-steps-as-non-root.yaml > run-steps-as-non-root.yaml
    - name: extract-task
      image: quay.io/ibmgaragecloud/alpine-curl
      script: |
        cd k8s
        head -n 24 run-steps-as-non-root.yaml > run-steps-as-non-root-task-only.yaml
    
    - name: swap-image
      image: quay.io/ibmgaragecloud/alpine-curl
      script: |
        cd k8s
        sed 's/ubuntu/quay.io\/ibmgaragecloud\/alpine-curl/g' run-steps-as-non-root-task-only.yaml > run-steps-as-non-root-alpine-task.yaml
        cat run-steps-as-non-root-alpine-task.yaml
